language: objective-c
before_install:
    - brew update
    - brew install xctool
script:
    - xctool test -scheme FactoryGentleman-Mac -workspace FactoryGentleman.xcworkspace
    - xctool test -scheme FactoryGentleman-iOS -workspace FactoryGentleman.xcworkspace -sdk iphonesimulator
