language: objective-c
before_install:
    - brew update
    - brew upgrade xctool
    - easy_install cpp-coveralls
    - gem install cocoapods
script:
    - xctool test -scheme FactoryGentleman-Mac -workspace FactoryGentleman.xcworkspace
    - xctool test -scheme FactoryGentleman-iOS -workspace FactoryGentleman.xcworkspace -sdk iphonesimulator
after_success:
    - coveralls -e Spec
