def needed_pods
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMockito'
end

target 'FactoryGentlemanSpec-iOS' do
  platform :ios, :deployment_target => 6.0
  needed_pods
end

target 'FactoryGentlemanSpec-Mac' do
  platform :osx, :deployment_target => 10.8
  needed_pods
end
